#!/usr/bin/env bash

sudo pacman -S --noconfirm man less ripgrep fd fzf jq stow

sudo pacman -S --noconfirm github-cli

sudo pacman -S --noconfirm wl-clipboard wl-clip-persist

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# 
# git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
# 
# sudo pacman -S swaync waybar greetd tuigreet xdg-desktop-portal-hyprland hyprpolkitagent yazi
# 
# sudo pacman -S ffmpeg 7zip jq poppler fd ripgrep fzf zoxide resvg imagemagick
# 
# sudo pacman -S fastfetch
# 
# sudo pacman -S rustup
# yay -S resvg
# 
# network-manager-applet

# clipse
