#!/usr/bin/env bash

# Note: These should be installed before boot otherwise they won't be available and there won't be anyway to connect to the internet.
sudo pacman -S --noconfirm networkmanager network-manager-applet

# General Utilities
sudo pacman -S --noconfirm man zsh tmux less ripgrep fd fzf jq stow qutebrowser firefox starship lazygit git-delta libnotify atuin openssl openssl-1.1 unzip xdg-utils pdfjs lsof

sudo pacman -S --noconfirm iwd impala

sudo pacman -S --noconfirm discord

sudo pacman -S --noconfirm bat

sudo pacman -S --noconfirm posgresql

sudo pacman -S --noconfirm docker docker-buildx docker-compose

sudo pacman -S --noconfirm zsh-autosuggestions zsh-syntax-highlighting

sudo pacman -S --noconfirm github-cli

sudo pacman -S --noconfirm wl-clipboard wl-clip-persist

sudo pacman -S --noconfirm waybar

sudo pacman -S --noconfirm bluez bluez-utils bluetui

sudo pacman -S --noconfirm swaync

sudo pacman -S --noconfirm xdg-desktop-portal-hyprland

sudo pacman -S --noconfirm hyprpolkitagent

sudo pacman -S --noconfirm hypridle

sudo pacman -S --noconfirm hyprlock

sudo pacman -S --noconfirm hyprpaper

sudo pacman -S --noconfirm fastfetch

sudo pacman -S --noconfirm brightnessctl

sudo pacman -S --noconfirm pavucontrol

sudo pacman -S --noconfirm ttf-meslo-nerd

sudo pacman -S --noconfirm ttf-liberation-mono-nerd

sudo pacman -S --noconfirm ttf-font-awesome ttf-jetbrains-mono-nerd

sudo pacman -S --noconfirm nordvpn-bin

sudo pacman -S --noconfirm dmidecode

sudo pacman -S --noconfirm lshw

sudo pacman -S --noconfirm calibre

# Rust toolchain
sudo pacman -S --noconfirm lld clang

curl https://mise.run | sh

# Yazi & deps
sudo pacman -S --noconfirm yazi ffmpeg 7zip jq poppler zoxide imagemagick

# Install Paru Start
sudo pacman -S --noconfirm base-devel rustup
sudo pacman -S --noconfirm rustup
rustup default stable
git clone https://aur.archlinux.org/paru.git ~/paru
cd ~/paru
makepkg -si
cd ~/dotfiles
# Install Paru Start

paru -S --noconfirm clipse

# Yazi dep
paru -S resvg

paru -S spotify

paru -S lazydocker

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# Login Manager Start
sudo pacman -S --noconfirm greetd
sudo pacman -S --noconfirm greetd-tuigreet

# NOTE: Need to run manually
# sudo systemctl disable sddm
# sudo systemctl enable greetd
# sudo systemctl start greetd
# sudo systemctl stop sddm
# sudo pacman -R sddm
# Login Manager End

sudo pacman -R kitty dolphin
