#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install bitwarden

brew install --cask nikitabobko/tap/aerospace

brew install stow

brew install gh

gh extension install dlvhdr/gh-dash

brew install zsh-autosuggestions

brew install zsh-syntax-highlighting

brew install --cask ghostty

brew install neovim

brew install tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

curl https://mise.run | sh

curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
sudo installer -pkg AWSCLIV2.pkg -target /

curl "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-arm64.pkg" -o "aws-sam-cli-macos-arm64.pkg"
sudo installer -pkg aws-sam-cli-macos-arm64.pkg -target /

brew install orbstack
