
--[[ dap.adapters.php = { ]]
--[[ 	type = "executable", ]]
--[[ 	command = "nodejs", ]]
--[[ 	args = { "/home/johnredd/Downloads/vscode-php-debug-1.28.0/out/paths.js" }, ]]
--[[ 	args = {"/opt/vscode-php-debug/out/phpDebug.js"}, ]]
--[[ } ]]

--[[ dap.configurations.php = { ]]
--[[ 	{ ]]
--[[ 		type = "php", ]]
--[[ 		request = "launch", ]]
--[[ 		name = "Listen for xdebug", ]]
--[[ 		port = "9003", ]]
--[[ 		log = true, ]]
--[[ 		serverSourceRoot = '/srv/www/', ]]
--[[ 		localSourceRoot = '/home/www/VVV/www/', ]]
--[[ 	}, ]]
--[[ } ]]
