-- require('copilot').setup({
--   panel = {
--     enabled = true,
--     auto_refresh = false,
--     keymap = {
--       jump_prev = "[[",
--       jump_next = "]]",
--       accept = "<CR>",
--       refresh = "gr",
--       open = "<M-CR>"
--     },
--     layout = {
--       position = "bottom", -- | top | left | right
--       ratio = 0.4
--     },
--   },
--   suggestion = {
--     enabled = true,
--     auto_trigger = false,
--     debounce = 75,
--     keymap = {
--       accept = "<C-l>",
--       accept_word = false,
--       accept_line = false,
--       next = "<C-]>",
--       prev = "<C-[>",
--       dismiss = "<A-]>",
--     },
--   },
--   filetypes = {
--     yaml = false,
--     markdown = false,
--     help = false,
--     gitcommit = false,
--     gitrebase = false,
--     hgcommit = false,
--     svn = false,
--     cvs = false,
--     ["."] = false,
--   },
--   copilot_node_command = 'node', -- Node.js version must be > 16.x
--   server_opts_overrides = {},
-- })

-- local suggestion = require("copilot.suggestion")
-- .is_visible()
-- require("copilot.suggestion").accept()
-- require("copilot.suggestion").accept_word()
-- require("copilot.suggestion").accept_line()
-- require("copilot.suggestion").next()
-- require("copilot.suggestion").prev()
-- require("copilot.suggestion").dismiss()
-- require("copilot.suggestion").toggle_auto_trigger()


-- vim.keymap.set("n", "<leader>cn", suggestion.next)
-- vim.keymap.set("n", "<leader>cp", suggestion.prev)
-- vim.keymap.set("n", "<leader>cd", suggestion.dismiss)
-- vim.keymap.set("n", "<leader>cl", suggestion.accept)
